set project_directory [get_property DIRECTORY [current_project]]
set project [get_property NAME [current_project]]
set rom_module drp_variable_rom_crdb_vu9
set gt_module xilinx_gty_crdb_vu9
create_ip -name gtwizard_ultrascale -vendor xilinx.com -library ip -version 1.7 -module_name $gt_module
set_property -dict [list CONFIG.CHANNEL_ENABLE {X1Y20 X1Y21 X1Y22 X1Y23 X1Y24 X1Y25} CONFIG.TX_MASTER_CHANNEL {X1Y20} CONFIG.RX_MASTER_CHANNEL {X1Y20} CONFIG.TX_LINE_RATE {15.2} CONFIG.TX_USER_DATA_WIDTH {64} CONFIG.RX_LINE_RATE {15.2} CONFIG.RX_USER_DATA_WIDTH {64} CONFIG.RX_BUFFER_MODE {0} CONFIG.RX_BUFFER_BYPASS_MODE {SINGLE} CONFIG.ENABLE_OPTIONAL_PORTS {drpaddr_common_in drpaddr_in drpclk_common_in drpclk_in drpdi_common_in drpdi_in drpen_common_in drpen_in drpwe_common_in drpwe_in drpdo_common_out drpdo_out drprdy_common_out drprdy_out} CONFIG.TX_PLL_TYPE {QPLL0} CONFIG.RX_PLL_TYPE {QPLL0} CONFIG.RX_REFCLK_SOURCE {X1Y20 clk0+1 X1Y21 clk0+1 X1Y22 clk0+1 X1Y23 clk0+1 X1Y24 clk0 X1Y25 clk0 } CONFIG.TX_REFCLK_SOURCE { X1Y20 clk0+1 X1Y21 clk0+1 X1Y22 clk0+1 X1Y23 clk0+1 X1Y24 clk0 X1Y25 clk0} CONFIG.LOCATE_TX_USER_CLOCKING {CORE} CONFIG.LOCATE_RX_USER_CLOCKING {CORE} CONFIG.TX_QPLL_FRACN_NUMERATOR {0} CONFIG.RX_QPLL_FRACN_NUMERATOR {0} CONFIG.TX_REFCLK_FREQUENCY {100} CONFIG.TX_INT_DATA_WIDTH {32} CONFIG.RX_REFCLK_FREQUENCY {100} CONFIG.RX_INT_DATA_WIDTH {32} CONFIG.FREERUN_FREQUENCY {150} CONFIG.RX_COMMA_SHOW_REALIGN_ENABLE {false} CONFIG.RX_SLIDE_MODE {PCS} CONFIG.RX_COMMA_ALIGN_WORD {2} ] [get_ips $gt_module]
generate_target {instantiation_template} [get_files $project_directory/$project.srcs/sources_1/ip/$gt_module/$gt_module.xci]
update_compile_order -fileset sources_1
create_ip -name blk_mem_gen -vendor xilinx.com -library ip -module_name $rom_module
set_property -dict [list CONFIG.Memory_Type {Single_Port_ROM} CONFIG.Write_Width_A {42} CONFIG.Write_Depth_A {183} CONFIG.Load_Init_File {true} CONFIG.Coe_File "${src_directory}/coe/maxilink_9567272f2a6616584074.coe" CONFIG.Read_Width_A {42} CONFIG.Write_Width_B {42} CONFIG.Read_Width_B {42} CONFIG.Port_A_Write_Rate {0}] [get_ips $rom_module]
generate_target {instantiation_template} [get_files /$project_directory/$project.srcs/sources_1/ip/$rom_module/$rom_module.xci]
